/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-northeast-1",
    "aws_cognito_identity_pool_id": "ap-northeast-1:dea775d5-a79b-4436-992f-47a307c07fba",
    "aws_cognito_region": "ap-northeast-1",
    "aws_user_pools_id": "ap-northeast-1_d5cN3cyel",
    "aws_user_pools_web_client_id": "5oa8se42qk9ba109quoa8b6s2p",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://xomko6p7t5aixlrfyipqst2bye.appsync-api.ap-northeast-1.amazonaws.com/graphql",
    "aws_appsync_region": "ap-northeast-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS"
};


export default awsmobile;
